USE [MedicalRecordDB]
GO

INSERT INTO EXTBDC1 (PID,
DOC_NO,
ACTIVE_FLG,
DOC_DATAX)
VALUES
('8888000059','0A497E6023CCBA2014030315120300','1','<DOC><DRPROGRESS><DOCHEAD></DOCHEAD><BODY><PLOBLEM id="1"><FREEG><HTMLDATA></HTMLDATA></FREEG></PLOBLEM><SUBJECTIVE id="2"><FREEG><HTMLDATA>&lt;DIV&gt;＜主訴＞1週間前から便に血が混ざる。&lt;BR&gt;＜現病歴＞1週間前から便に血が混ざり、佐藤クリニックより大腸がんの疑いで紹介。当院内科受診、大腸ファイバで左下行結腸のがんと診断。&lt;BR&gt;＜既往歴＞現在糖尿病でオイグルコン2.5mg内服コントロール中。&lt;/DIV&gt;</HTMLDATA><FREE>＜主訴＞1週間前から便に血が混ざる。</FREE><FREE>＜現病歴＞1週間前から便に血が混ざり、佐藤クリニックより大腸がんの疑いで紹介。当院内科受診、大腸ファイバで左下行結腸のがんと診断。</FREE><FREE>＜既往歴＞現在糖尿病でオイグルコン2.5mg内服コントロール中。</FREE></FREEG></SUBJECTIVE><OBJECTIVE id="3"><FREEG><HTMLDATA>&lt;DIV&gt;＜入院時身体所見＞特記事項なし&lt;BR&gt;＜入院時検査所見＞特になし&lt;/DIV&gt;</HTMLDATA><FREE>＜入院時身体所見＞特記事項なし</FREE><FREE>＜入院時検査所見＞特になし</FREE></FREEG></OBJECTIVE><ASSESSMENT id="4"><FREEG><HTMLDATA></HTMLDATA></FREEG></ASSESSMENT><PLAN id="5"><FREEG><HTMLDATA>&lt;DIV&gt;＜治療方針＞手術目的で外科紹介&lt;/DIV&gt;</HTMLDATA><FREE>＜治療方針＞手術目的で外科紹介</FREE></FREEG></PLAN></BODY></DRPROGRESS></DOC>'),
('8888000059','0A497E60250CDB2014030315132500','1','<DOC><DRPROGRESS><DOCHEAD></DOCHEAD><BODY><PLOBLEM id="1"><FREEG><HTMLDATA></HTMLDATA></FREEG></PLOBLEM><SUBJECTIVE id="2"><FREEG><HTMLDATA></HTMLDATA></FREEG></SUBJECTIVE><OBJECTIVE id="3"><FREEG><HTMLDATA></HTMLDATA></FREEG></OBJECTIVE><ASSESSMENT id="4"><FREEG><HTMLDATA>&lt;DIV&gt;＜臨床経過＞生検実施。生検でＧｒｏｕｐⅤ。ＳＭからＳＳ癌と考えられる。&lt;/DIV&gt;</HTMLDATA><FREE>＜臨床経過＞生検実施。生検でＧｒｏｕｐⅤ。ＳＭからＳＳ癌と考えられる。</FREE></FREEG></ASSESSMENT><PLAN id="5"><FREEG><HTMLDATA></HTMLDATA></FREEG></PLAN></BODY></DRPROGRESS></DOC>'),
('8888001192','0A497E602D52782014030315222700','1','<DOC><DRPROGRESS><DOCHEAD></DOCHEAD><BODY><PLOBLEM id="1"><FREEG><HTMLDATA></HTMLDATA></FREEG></PLOBLEM><SUBJECTIVE id="2"><FREEG><HTMLDATA>&lt;DIV&gt;1週間前から便に血が混ざる。佐藤クリニックより大腸がんの疑いで紹介。当院内科受診、大腸ファイバで左下行結腸のがんと診断。&lt;BR&gt;既往として現在糖尿病でオイグルコン2.5mg内服コントロール中。&lt;/DIV&gt;</HTMLDATA><FREE>1週間前から便に血が混ざる。佐藤クリニックより大腸がんの疑いで紹介。当院内科受診、大腸ファイバで左下行結腸のがんと診断。</FREE><FREE>既往として現在糖尿病でオイグルコン2.5mg内服コントロール中。</FREE></FREEG></SUBJECTIVE><OBJECTIVE id="3"><FREEG><HTMLDATA>&lt;DIV&gt;入院時の身体所見としては特記事項なし&lt;/DIV&gt;</HTMLDATA><FREE>入院時の身体所見としては特記事項なし</FREE></FREEG></OBJECTIVE><ASSESSMENT id="4"><FREEG><HTMLDATA></HTMLDATA></FREEG></ASSESSMENT><PLAN id="5"><FREEG><HTMLDATA>&lt;DIV&gt;手術目的で外科紹介の方針&lt;/DIV&gt;</HTMLDATA><FREE>手術目的で外科紹介の方針</FREE></FREEG></PLAN></BODY></DRPROGRESS></DOC>'),
('8888001192','0A497E602DC67F2014030315225700','1','<DOC><DRPROGRESS><DOCHEAD></DOCHEAD><BODY><PLOBLEM id="1"><FREEG><HTMLDATA></HTMLDATA></FREEG></PLOBLEM><SUBJECTIVE id="2"><FREEG><HTMLDATA></HTMLDATA></FREEG></SUBJECTIVE><OBJECTIVE id="3"><FREEG><HTMLDATA></HTMLDATA></FREEG></OBJECTIVE><ASSESSMENT id="4"><FREEG><HTMLDATA>&lt;DIV&gt;生検実施。生検でＧｒｏｕｐⅤ。ＳＭからＳＳ癌と考えられる。&lt;/DIV&gt;</HTMLDATA><FREE>生検実施。生検でＧｒｏｕｐⅤ。ＳＭからＳＳ癌と考えられる。</FREE></FREEG></ASSESSMENT><PLAN id="5"><FREEG><HTMLDATA></HTMLDATA></FREEG></PLAN></BODY></DRPROGRESS></DOC>')