CREATE TABLE EXTBOD1 (
  PID VARCHAR(20),
  DOC_NO VARCHAR(30),
  SEQ INT,
  ACTIVE_FLG BIT,
  DOCDATE VARCHAR(20),
  ODRNO VARCHAR(20),
  DOC_K VARCHAR(20),
  ICODE VARCHAR(20),
  IATTR VARCHAR(20),
  INAME NVARCHAR(50),
  NUM INT,
  UKIND VARCHAR(20),
  UCODE VARCHAR(20),
  UNAME NVARCHAR(20),
  TAG_NAME VARCHAR(20),
  TOOL_VDATA NVARCHAR(MAX)
);